### ISSUE TITLE
What are our six sections of the day?

### ISSUE THREAD

**Issue by tommeagher** [tswicegood/python-data-science-intro#2]
Here's my stab at one way we might break up the 2 hours. What do you think?
- Part One
  - iPython interpreter/notebook
  - pandas
    - What is a series? What is a dataframe?
    - How do I read in data?
    - How can I clean data?
  - A hands-on exercise
- Part Two
  - pandas
    - More cleaning and transposing of tables
    - aggregating, groupbys, sorting
  - plotting your data in simple bar charts, line graphs and scatter plots
  - More hands-on exercise

**Comment by tswicegood** [comment]
Let's generalize the very first piece, instead of IPython, let's do "intro to the tools".  I'm thinking something along the lines of:
- Quick note on Anaconda and `conda`
- Creating an environment to work in (`conda create -n work anaconda`)
- Launching `ipython` and `ipython notebook`

That would cover 15 - 20 minutes of material and hands on, then start working with `pandas`.  I think there's a ton of material we can do here.  Maybe break it down into a series of "here's how you do X, Y, and Z.  Now go find some interesting information out."  We could build progressively thorughout the class, then for the last 15 - 30 minute block we could start ramping up on plotting inside the notebook.

Thoughts?

---

Side note, [this blog post](http://pbpython.com/excel-pandas-comp.html) and [the followup](http://pbpython.com/excel-pandas-comp-2.html) has some examples of things you do with Excel and how to do them in pandas with a great jumping off into territory that's not so easily covered by a spreadsheet.

**Comment by tommeagher** [comment]
I will admit I know next to nothing about conda and have only used Anaconda a bit. I think it's great to introduce folks to it as one way to manage packages and envs, as long as we acknowledge a lot of people use iPython and notebooks in general even without Anaconda. 

I think your idea for the outline is fine. Can you flesh it out a bit for both sessions in general? I'm starting to feel the looming clock ticking and not sure how we can get started. I'd love to have the sections defined and one of our names assigned to each part so I can start coding a few pieces.

And I'm assuming we'll have the whole thing laid out in a notebook or series of notebooks, right? Can we shoot for, say, Monday or Tuesday, as a deadline to have it all done?

**Comment by tswicegood** [comment]
> I will admit I know next to nothing about conda and have only used Anaconda a bit. I think it's great to introduce folks to it as one way to manage packages and envs, as long as we acknowledge a lot of people use iPython and notebooks in general even without Anaconda.

Agreed.  I want to mention them as just basically "anaconda is the easiest way to get the scientific stack up and running on any platform and conda lets you reproduce your work really easily so other's can work with your code."  Not a focal point, just something to touch on.

> And I'm assuming we'll have the whole thing laid out in a notebook or series of notebooks, right? Can we shoot for, say, Monday or Tuesday, as a deadline to have it all done?

That sounds doable.  I'll take a stab at a little more of an outline tomorrow, maybe in README form against this repo with slots for us to drop in notebooks and/or markdown files (as appropriate) for the sections then we can figure out how to divvy everything up from there.

**Comment by tommeagher** [comment]
Awesome. This sounds like we're on the same page. If you can put that README together, I'll put my name next to a few sections and get cracking. 

Thank you!

**Comment by tswicegood** [comment]
Closing in favor of PRs
